### ISSUE TITLE
Create Landing/Main Ideas Page

### ISSUE THREAD

**Issue by razzlepdx** [Web-Bakers/web-bakers#5]

**Comment by reuben-jones** [comment]
Checklist:
- Consider removing tags for now?
- Add comments icon for each idea
- Add voting?
- Add flag for inappropriate content
- Add "add to watchlist" button?
- Add title and description for the ideas submission box
- Add other inputs for idea submission, to appear when the focus is on the main input
-- Blurb/description (author and submission timestamp are added automatically)
- Link up post route so that the form adds a new idea to the ideas page
-- Get data from form and add to ideas array
-- Redirect/refresh ideas page

**Comment by reuben-jones** [comment]
Done:

- Link up post route so that the form adds a new idea to the ideas page
-- Get data from form and add to ideas array
-- Redirect/refresh ideas page

**Comment by reuben-jones** [comment]
Done: 
- Add title and description for the ideas submission box

**Comment by reuben-jones** [comment]
Done: 
- Add other inputs for idea submission, to appear when the focus is on the main input
-- Blurb/description (author and submission timestamp are added automatically)

NB: Used jQuery .slideDown(200)

**Comment by reuben-jones** [comment]
Done: 
- Add comments icon for each idea
- Add voting?
- Add flag for inappropriate content
- Add "add to watchlist" button?

NB: Just hardcoded stuff in for now. Wiring them up seems like it would be better split into smaller stories.
